---
title: "mi_jj_mdhhs_non_subsidy"
author: "Andrew Byrum"
date: "12/15/2021"
output: html_document
---

```{r include=FALSE}
### call libraries
library(easypackages)
libraries("tidyverse","foreign","lubridate","reshape2", "ggplot2","RColorBrewer","knitr","forcats","openxlsx","statar","svDialogs","xlsx", "magrittr","stringr", "data.table","janitor","kableExtra","leaflet", "readr", "rmarkdown","rowr", "gganimate", "gifski","tidycensus","sf","htmltools","acs","tigris","mapview","rgeos", "ggrepel", "censusxy","gdata","lavaan","mclust","tmap", "raster","rgeos","gmapsdistance","viridis","cowplot","lintr","leaflet.extras","censusapi","data.table","gridGraphics","readxl","haven","ggridges","extrafont","extrafontdb","datamodelr","Lahman","DiagrammeR","fs","readxl","rsvg","V8","tidylog","distill","ragg")
```

```{r include=FALSE}
mdhhs_non_subsidy <- readr::read_delim("C:\\Users\\abyrum\\The Council of State Governments\\JC Research - Documents\\JC Research - JJ_Michigan - JJ_Michigan\\Data\\Raw\\MDHHS\\Financial\\All Non-Subsidy Payments FY17-FY21 - REQ 25962 - 2021-12-31\\All Non-Subsidy Payments FY17-FY21 - 2021-12-31.txt", delim = "\t")

### filter for iv-e funding source only
mdhhs_non_subsidy_iv_e_only <- mdhhs_non_subsidy %>% 
  filter(grant_fund_src_desc == "IV-E")
```

```{r include=FALSE}
csg_fiscal_year <- function(x, fy_start = NULL) {

  # make sure input date is date or posix format
  if (!all((lubridate::is.Date(x) || lubridate::is.POSIXt(x)))) {
    stop("Input vector must be Date or POSIX format.", call. = FALSE)
  }

  # make sure fiscal year start month is specified
  if (is.null(fy_start)) {
    stop("You must specify the starting month of the fiscal year", call. = FALSE)
  }

  # error if more than one starting month specified
  if (length(fy_start) > 1) {
    stop("You must specify only one starting month.", call. = FALSE)
  }

  # if fy start is character, try to parse month, error if month not matched
  if (is.character(fy_start)) {
    fy_start <- which(month.name == fy_start)

    if (length(fy_start) == 0) {
      stop("Please spell starting month correctly", call. = FALSE)
    }
  }

  # error if fiscal year start set january -- just use calendar year instead!
  if (fy_start == 1) {
    stop("Do you really want the fiscal year to start on January 1?", call. = FALSE)
  }

  # error if fy start not between feb and december
  if (!fy_start %in% 2:12) {
    stop("Not a valid starting month", call. = FALSE)
  }

  # extract year and month of input dates
  year  <- lubridate::year(x)
  month <- lubridate::month(x)

  # add 1 to year if month is after fiscal year start
  ifelse(month >= fy_start, year + 1, year)

  }
```


```{r include=FALSE}
### create list for jj and dual ward legal statuses
dual_ward_status_list <- c("52 - MCI Ward/44 and Act 150/46","90 - Temp Court Ward 42 and Delinquent Court Ward 40","91 -  Perm Court Ward 41 and Delinquent Court Ward 40","92 - Temp Court Ward 42 and Act 150/46","93 - Perm Court Ward 41 and Act 150/46","94 - MCI Ward/44 and Delinquent Court Ward/40","80 - In Home 42 and Delinquent Court Ward 40","82 - In Home 42 and Act 150/46")

state_ward_status_list <- c("40 - Court Ward Delinquent","46 - State Ward - Delinquent - Act 150","50 - Non-Ward With a Delinquent Petition Filed")

### code legal_status into two groups: dual ward and jj
### group records into fiscal years (october - september) using 
mdhhs_non_subsidy_iv_e_only %<>%
  clean_names() %>% 
  mutate(legal_status_ward_flag = case_when(
    legal_status_desc %in% state_ward_status_list ~ 1,
    legal_status_desc %in% dual_ward_status_list ~ 2,
    TRUE ~ as.numeric(NA))) %>% 
    # legal_status_ward_flag = factor(legal_status_ward_flag,
    #      levels = c(1,2),
    #      labels = c("JJ","Dual Ward"))) %>% ###  factor function to assign labels to values
  mutate(pymnt_end_dt = mdy(pymnt_end_dt)) %>% 
  mutate(services_provided_fy = csg_fiscal_year(pymnt_end_dt,"October"))
```

<br>

```{r echo=FALSE,warning=FALSE,message=FALSE}
mdhhs_non_subsidy_iv_e_table <- mdhhs_non_subsidy_iv_e_only %>% 
  filter(!is.na(legal_status_ward_flag)==TRUE,
         services_provided_fy %in% c(2017,2018,2019,2020)) %>% 
  group_by(services_provided_fy) %>% 
  summarize("JJ Only, Unique Youth" = n_distinct(seqval[legal_status_ward_flag==1]),
            "JJ Only, Federal Share" = scales::dollar(sum(federal_share_amt[legal_status_ward_flag==1], na.rm=TRUE)),
            "Dual Wards, Unique Youth" = n_distinct(seqval[legal_status_ward_flag==2]),
            "Dual Wards, Federal Share" = scales::dollar(sum(federal_share_amt[legal_status_ward_flag==2], na.rm=TRUE))) %>% 
  ungroup() %>% 
  mutate(services_provided_fy = as.character(services_provided_fy)) %>% 
  rename(`FY (Services Provided)` = services_provided_fy)

### print table via kableextra
kable(mdhhs_non_subsidy_iv_e_table, format.args = list(big.mark = ","), align=rep('c')) %>%
   kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), row_label_position = "l")
```

<br>

```{r echo=FALSE,warning=FALSE,message=FALSE}
theme_set(theme_minimal(20, base_family = "Calibri"))

mdhhs_non_subsidy_iv_e_table <- mdhhs_non_subsidy_iv_e_only %>% 
  filter(!is.na(legal_status_ward_flag)==TRUE,
         services_provided_fy %in% c(2017,2018,2019,2020)) %>% 
  group_by(services_provided_fy) %>% 
  summarize("JJ Only, Unique Youth" = n_distinct(seqval[legal_status_ward_flag==1]),
            "JJ Only, Federal Share" = sum(federal_share_amt[legal_status_ward_flag==1], na.rm=TRUE),
            "Dual Wards, Unique Youth" = n_distinct(seqval[legal_status_ward_flag==2]),
            "Dual Wards, Federal Share" = sum(federal_share_amt[legal_status_ward_flag==2], na.rm=TRUE)) %>% 
  ungroup() %>% 
  mutate(services_provided_fy = as.character(services_provided_fy)) %>% 
  rename(`FY (Services Provided)` = services_provided_fy)

### pivot table df
mdhhs_non_subsidy_iv_e_plot_a <- mdhhs_non_subsidy_iv_e_table %>%
  gather(federal_share, federal_value, `JJ Only, Federal Share`,`Dual Wards, Federal Share`) %>% 
  select(1,4,5) %>% 
  mutate(jj_dual_ward = ifelse(federal_share == "JJ Only, Federal Share","JJ Only","Dual Ward")) %>% 
  select(1,3,4)

mdhhs_non_subsidy_iv_e_plot_b <- mdhhs_non_subsidy_iv_e_table %>%
  gather(key, unique_youth_value, `JJ Only, Unique Youth`,`Dual Wards, Unique Youth`) %>% 
  select(1,4,5) %>% 
  mutate(jj_dual_ward = ifelse(key == "JJ Only, Unique Youth","JJ Only","Dual Ward")) %>% 
  select(1,3,4)

mdhhs_non_subsidy_iv_e_plot <- inner_join(mdhhs_non_subsidy_iv_e_plot_a,mdhhs_non_subsidy_iv_e_plot_b,by=c("FY (Services Provided)","jj_dual_ward"))

### plot
mi_iv_e_plot_1 <- ggplot(data = mdhhs_non_subsidy_iv_e_plot,
            mapping = aes(x = `FY (Services Provided)`, y = federal_value, fill = jj_dual_ward)) + 
  geom_bar(stat = "identity", position = "dodge", color = "gray80") +
  scale_fill_manual(values = c("#00475d","#0db4e4")) +
  scale_y_continuous(label=scales::label_number(prefix = "$", suffix = " M", scale = 1e-6, accuracy = 0.1)) +
  scale_x_discrete(labels = scales::wrap_format(18),limits = rev) +
  # geom_label(aes(x=2, y=2750000, label="$xM"),
  #          color="#007392",
  #          size=6, fontface="bold",fill = "white") +
  #   geom_label(aes(x=1, y=2500000, label="$xM"),                 
  #          color="#0db4e4", 
  #          size=6, fontface="bold",fill = "white") +
    theme_minimal() +
    theme(legend.position = "top",
        legend.title.align=0.5,
        axis.text=element_text(size=12),
        axis.title=element_text(size=14,face="bold"),
        legend.text = element_text(size=12),
        strip.text.x = element_text(face = "bold")) +
    labs(y = NULL, x = NULL,
      caption = NULL,
      title = NULL,
      subtitle = NULL,
      fill = NULL) +
    coord_flip() +
  guides(fill = guide_legend(reverse = TRUE)) + 
  geom_label_repel(aes(label = paste0(unique_youth_value," unique youth"), 
                                             group = jj_dual_ward),
                   position = position_dodge(width = .9),
                  direction = 'x',
                  hjust = 0.75,
                  label.padding = 0.3,
                  box.padding = 0.15,
                  size = 4,
                  fill = "white",
                  color = c("#0db4e4","#0db4e4","#0db4e4","#0db4e4",
                            "#00475d","#00475d","#00475d","#00475d"),
                  segment.color = NA,
                  fontface = "bold",
                  na.rm = TRUE,
                  show.legend = FALSE)

ggsave("C:\\Users\\abyrum\\The Council of State Governments\\JC Research - Documents\\JC Research - JJ_Michigan - JJ_Michigan\\Work Products\\Financial\\IV-E\\mi_iv_e_plot_1.png", mi_iv_e_plot_1, width = 8, height = 6)
```

